import type { Metadata } from "next"
import "./globals.css"
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "F1 API",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={"dark"}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
